name: 'Nrwl Nx'
author: 'Mansa Group'
description: 'Wrap the Nx monorepo tool and execute tasks depending on the action context'
inputs:
  targets:
    description: 'Comma-separated list of targets to execute'
    required: true
  projects:
    description: 'Comma-separated list of projects to use'
    required: false
  all: # Mutually exclusive with `affected`
    description: 'Run the targets on all projects'
    required: false
    default: 'false'
  affected: # Mutually exclusive with `all`
    description: "Use the Nx' affected subcommand to only process affected projects"
    required: false
    default: 'true'
  parallel:
    description: 'Run the tasks in parallel (can be expensive)'
    required: false
    default: 'false'
  maxParallel:
    description: 'Number of tasks to execute in parallel (can be expensive)'
    required: false
    default: '3'
  args:
    description: 'Optional arguments to append to the Nx command'
    required: false
    default: ''
  nxCloud:
    description: 'Enable support for Nx Cloud'
    required: false
    default: 'false'
  workingDirectory:
    description: 'Path to the Nx workspace, needed if not the repository root'
    required: false
  baseBoundaryOverride:
    description: 'Parameter to use for overriding nx base commit'
    required: false
  headBoundaryOverride:
    description: 'Parameter to use for overriding nx head commit'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'blue'
